require("options")
require("keymaps")
require("plugins")
require("colorscheme")
require("completion")
require("servers")
require("tree-sitter")
require("lsp-installer")
require("tele_scope")
require("spellCheck")

